### ISSUE TITLE
Release: Administrative Review

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/planetary-sdi#3]
This site requires an administrative review to ensure that no sensitive information is included.

**Comment by acpaquette** [comment]
- No PII

- One absolute file path found here:
https://github.com/jlaura/planetary-sdi/blob/ae53183d6f8cc6209d314174897627fd09549582/make_json_bib.sh#L3

- No internal server host names or IP addresses

- No Usernames/Passwords

**Comment by jlaura** [comment]
Fixed by [53373a9](https://github.com/USGS-Astrogeology/planetary-sdi/commit/53373a9cfd1b212a111d57adc0a28c731b24bc5c)
